/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.HeadlessException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author vinicius.castro
 */
public class CadastarGasto extends javax.swing.JFrame {

    /**
     * Creates new form CadastarGasto
     */
    public CadastarGasto() {
        initComponents();
        btnConsultarGastos.setToolTipText("Consultar Gastos");
        btnSalvar.setToolTipText("Salvar");
        txtLocal.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnConsultarGastos = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpcoes = new javax.swing.JMenu();
        menuItConsutarGastos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCFP - Cadastar Gastos");

        jToolBar1.setRollover(true);

        btnConsultarGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/search.png"))); // NOI18N
        btnConsultarGastos.setFocusable(false);
        btnConsultarGastos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultarGastos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultarGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarGastosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConsultarGastos);

        jLabel1.setText("Local*");

        jLabel2.setText("Valor*");

        jLabel3.setText("Data*");

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/save.png"))); // NOI18N
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        menuOpcoes.setText("Opções");

        menuItConsutarGastos.setText("Consutar Gastos");
        menuItConsutarGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItConsutarGastosActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuItConsutarGastos);

        jMenuBar1.add(menuOpcoes);

        jMenu2.setText("Ajuda");

        menuItAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuItAjuda.setText("Sobre o Sistema");
        menuItAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItAjudaActionPerformed(evt);
            }
        });
        jMenu2.add(menuItAjuda);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(txtValor, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarGastosActionPerformed
        if (evt.getSource() == btnConsultarGastos) {
            ConsultarGasto consGasto = new ConsultarGasto();
            consGasto.setResizable(true);
            consGasto.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnConsultarGastosActionPerformed

    private void menuItConsutarGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItConsutarGastosActionPerformed
        if (evt.getSource() == menuItConsutarGastos) {
            ConsultarGasto consGasto = new ConsultarGasto();
            consGasto.setResizable(true);
            consGasto.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_menuItConsutarGastosActionPerformed

    private void menuItAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItAjudaActionPerformed
        JOptionPane.showMessageDialog(null, "Sistemas de Controle de Gastos Financeiro\n"
                + "Desenvolvido por Vinicius Castro\n"
                + "Contato: vinicius1595@gmail.com\n\n"
                + "Copyright © Todos Direitos Reservados");
    }//GEN-LAST:event_menuItAjudaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        boolean verif = true;
        String falta = "";

        if (txtLocal.getText().equals("") || txtLocal == null) {
            verif = false;
            falta += "local ";
        }
        if (txtValor.getText().equals("") || txtValor == null) {
            verif = false;
            falta += "valor ";
        }
        if (txtData == null || txtData.getText().equals("")) {
            verif = false;
            falta += "data";
        }

        if (verif) {
            String local, data, valor;
            local = txtLocal.getText();
            data = txtData.getText();
            valor = txtValor.getText();
            Gastos gasto = new Gastos(local, data, valor);
            File arquivo = new File("Arquivo/gasto.txt");
            try {
                try (FileWriter fw = new FileWriter(arquivo, true); BufferedWriter bw = new BufferedWriter(fw)) {
                    bw.write(gasto.local.toLowerCase() + "\t");
                    bw.write(gasto.data.toLowerCase() + "\t");
                    bw.write(gasto.valorCompra.toLowerCase());
                    bw.newLine();
                }
                JOptionPane.showMessageDialog(null, "Cadastro de gasto feito com sucesso!");
                txtData.setText("");
                txtLocal.setText("");
                txtValor.setText("");
            } catch (IOException | HeadlessException e) {
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você deve preencher todos os campos! (Faltou: " + falta + ")");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastarGasto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarGastos;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuItAjuda;
    private javax.swing.JMenuItem menuItConsutarGastos;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
