/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vinicius.castro
 */
public class ConsultarGasto extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarGasto
     */
    public ConsultarGasto() {
        initComponents();
        btnCadastrarGasto.setToolTipText("Cadastrar Gasto");
        txtConsulta.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnCadastrarGasto = new javax.swing.JButton();
        cbbTipoConsulta = new javax.swing.JComboBox<>();
        txtConsulta = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        txtLocal = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnExcluirGasto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpcoes = new javax.swing.JMenu();
        menuItCadastrarGasto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItAjuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SCFP - Consultar Gastos");

        jToolBar1.setRollover(true);

        btnCadastrarGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/inbox.png"))); // NOI18N
        btnCadastrarGasto.setFocusable(false);
        btnCadastrarGasto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarGasto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastrarGasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCadastrarGastoMouseReleased(evt);
            }
        });
        btnCadastrarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarGastoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCadastrarGasto);

        cbbTipoConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local", "Data", " " }));

        txtConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        txtLocal.setEditable(false);
        txtLocal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtLocal.setFocusCycleRoot(true);

        txtValor.setEditable(false);

        txtData.setEditable(false);

        jLabel1.setText("Local");

        jLabel2.setText("Valor");

        jLabel3.setText("Data");

        btnExcluirGasto.setText("Excluir Gasto");
        btnExcluirGasto.setEnabled(false);
        btnExcluirGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirGastoActionPerformed(evt);
            }
        });

        menuOpcoes.setText("Opções");

        menuItCadastrarGasto.setText("Cadastrar Gasto");
        menuItCadastrarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItCadastrarGastoActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuItCadastrarGasto);

        jMenuBar1.add(menuOpcoes);

        jMenu2.setText("Ajuda");

        menuItAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuItAjuda.setText("Sobre o Sistema");
        menuItAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItAjudaActionPerformed(evt);
            }
        });
        jMenu2.add(menuItAjuda);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(cbbTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcluirGasto)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar))
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbTipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnExcluirGasto)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarGastoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarGastoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarGastoMouseReleased

    private void menuItCadastrarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItCadastrarGastoActionPerformed
        if (evt.getSource() == menuItCadastrarGasto) {
            CadastarGasto cadGasto = new CadastarGasto();
            cadGasto.setResizable(true);
            cadGasto.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_menuItCadastrarGastoActionPerformed

    private void btnCadastrarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarGastoActionPerformed
        if (evt.getSource() == btnCadastrarGasto) {
            CadastarGasto cadGasto = new CadastarGasto();
            cadGasto.setResizable(true);
            cadGasto.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCadastrarGastoActionPerformed

    private void menuItAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItAjudaActionPerformed
        JOptionPane.showMessageDialog(null, "Sistemas de Controle de Gastos Financeiro\n"
                + "Desenvolvido por Vinicius Castro\n"
                + "Contato: vinicius1595@gmail.com\n\n"
                + "Copyright © Todos Direitos Reservados");
    }//GEN-LAST:event_menuItAjudaActionPerformed
    public void consultaPesquisa() throws IOException {
        Gastos gasto;
        System.out.println(txtConsulta);
        if (txtConsulta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o campo de pesquisa!");
        } else {
            String informacao, registro;
            informacao = txtConsulta.getText();
            informacao = informacao.toLowerCase();
            String[] inf = procurarGasto(informacao).split(",");
            System.out.println(procurarGasto(informacao));
            System.out.println(inf[0] + "njandskj");
            if (!(inf[0].equals(""))) {
                btnExcluirGasto.setEnabled(true);
                txtLocal.setText(inf[0]);
                txtData.setText(inf[1]);
                txtValor.setText(inf[2]);
            } else {
                txtLocal.setText("");
                txtData.setText("");
                txtValor.setText("");
                btnExcluirGasto.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Não ha dados");
            }
        }

    }

    public static String procurarGasto(String informacao) throws IOException {
        ControlaArquivo controlaArquivo = new ControlaArquivo();
        Gastos gasto;
        String guardaGasto = "";
        int i = 1;
        controlaArquivo.abrirGastoParaLeitura();
        while ((gasto = controlaArquivo.leGasto()) != null) {
            if (gasto.local.contains(informacao)) {
                guardaGasto += gasto.local + "," + gasto.data + "," + gasto.valorCompra + "\n";
                i++;
            }
        }
        System.out.println(guardaGasto);
        controlaArquivo.fecharGastoLeitura();
        return guardaGasto;
    }


    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {

            consultaPesquisa();
        } catch (IOException ex) {
            Logger.getLogger(ConsultarGasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirGastoActionPerformed
        Gastos gasto;
        String guardaGasto = "";
        int i = 1;
        try {
            String local = txtConsulta.getText();
            ControlaArquivo controlaArquivo = new ControlaArquivo();
            controlaArquivo.abrirGastoParaLeitura();
            controlaArquivo.excluiGasto(local);
            controlaArquivo.fecharGastoLeitura();
            txtLocal.setText("");
            txtData.setText("");
            txtValor.setText("");
            txtConsulta.setText("");

        } catch (IOException ex) {
            Logger.getLogger(ConsultarGasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcluirGastoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarGasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarGasto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarGasto;
    private javax.swing.JButton btnExcluirGasto;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbbTipoConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuItAjuda;
    private javax.swing.JMenuItem menuItCadastrarGasto;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
