/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import javax.swing.JOptionPane;

/**
 *
 * @author vinicius.castro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        btnCadastrarGasto.setToolTipText("Cadastrar Gasto");
        btnConsultarGastos.setToolTipText("Consultar Gastos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnCadastrarGasto = new javax.swing.JButton();
        btnConsultarGastos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuOpcoes = new javax.swing.JMenu();
        menuItCadastrarGasto = new javax.swing.JMenuItem();
        menuItConsutarGastos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItAjuda = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas de Controle Financeiro Pessoal");

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 20)); // NOI18N
        jLabel1.setText("Sistemas de Controle Financeiro Pessoal");

        jToolBar1.setRollover(true);

        btnCadastrarGasto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/inbox.png"))); // NOI18N
        btnCadastrarGasto.setFocusable(false);
        btnCadastrarGasto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarGasto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCadastrarGasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCadastrarGastoMouseReleased(evt);
            }
        });
        btnCadastrarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarGastoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCadastrarGasto);

        btnConsultarGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/search.png"))); // NOI18N
        btnConsultarGastos.setFocusable(false);
        btnConsultarGastos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultarGastos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultarGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarGastosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConsultarGastos);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/capa.png"))); // NOI18N

        menuOpcoes.setText("Opções");

        menuItCadastrarGasto.setText("Cadastrar Gasto");
        menuItCadastrarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItCadastrarGastoActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuItCadastrarGasto);

        menuItConsutarGastos.setText("Consutar Gastos");
        menuItConsutarGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItConsutarGastosActionPerformed(evt);
            }
        });
        menuOpcoes.add(menuItConsutarGastos);

        jMenuBar1.add(menuOpcoes);

        jMenu2.setText("Ajuda");

        menuItAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuItAjuda.setText("Sobre o Sistema");
        menuItAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItAjudaActionPerformed(evt);
            }
        });
        jMenu2.add(menuItAjuda);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarGastoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarGastoMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastrarGastoMouseReleased

    private void btnCadastrarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarGastoActionPerformed
        CadastarGasto cadGasto = new CadastarGasto();
        cadGasto.setResizable(true);
        cadGasto.setVisible(true);
    }//GEN-LAST:event_btnCadastrarGastoActionPerformed

    private void btnConsultarGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarGastosActionPerformed
        ConsultarGasto consGasto = new ConsultarGasto();
        consGasto.setResizable(true);
        consGasto.setVisible(true);
    }//GEN-LAST:event_btnConsultarGastosActionPerformed

    private void menuItCadastrarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItCadastrarGastoActionPerformed
        CadastarGasto cadGasto = new CadastarGasto();
        cadGasto.setResizable(true);
        cadGasto.setVisible(true);
    }//GEN-LAST:event_menuItCadastrarGastoActionPerformed

    private void menuItConsutarGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItConsutarGastosActionPerformed
        ConsultarGasto consGasto = new ConsultarGasto();
        consGasto.setResizable(true);
        consGasto.setVisible(true);
    }//GEN-LAST:event_menuItConsutarGastosActionPerformed

    private void menuItAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItAjudaActionPerformed
        JOptionPane.showMessageDialog(null, "Sistemas de Controle de Gastos Financeiro\n"
                + "Desenvolvido por Vinicius Castro\n"
                + "Contato: vinicius1595@gmail.com\n\n"
                + "Copyright © Todos Direitos Reservados");
    }//GEN-LAST:event_menuItAjudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarGasto;
    private javax.swing.JButton btnConsultarGastos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuItAjuda;
    private javax.swing.JMenuItem menuItCadastrarGasto;
    private javax.swing.JMenuItem menuItConsutarGastos;
    private javax.swing.JMenu menuOpcoes;
    // End of variables declaration//GEN-END:variables
}
